[package]
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "fedimint-escrow-client"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
cli = ["dep:clap"]
default = []

[dependencies]
anyhow = { workspace = true }
async-stream = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true, optional = true }
erased-serde = { workspace = true }
fedimint-api-client = { workspace = true }
fedimint-client-module = { workspace = true }
fedimint-core = { workspace = true }
fedimint-derive-secret = { workspace = true }
fedimint-escrow-common = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-server-core = { workspace = true }
frost-secp256k1 = { version = "3.0.0", features = ["serde"] }
futures = { workspace = true }
hex = { workspace = true }
ring = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
