[package]
authors.workspace = true
description.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "fedimint-escrow-tests"
readme.workspace = true
repository.workspace = true
version.workspace = true

[[test]]
name = "fedimint_escrow_tests"
path = "tests/tests.rs"

[dependencies]
fedimint-client = { workspace = true }
fedimint-core = { workspace = true }
fedimint-dummy-client = { workspace = true }
fedimint-dummy-server = { workspace = true }
fedimint-escrow-client = { workspace = true }
fedimint-escrow-common = { workspace = true }
fedimint-escrow-server = { workspace = true }
fedimint-testing = { workspace = true }
frost-secp256k1-tr = { version = "3.0.0", features = ["serde"] }
futures = { workspace = true }
iroh = { workspace = true, default-features = false }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
